apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyTrade-dotnet-api
  labels:
    app: MyTrade-dotnet-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MyTrade-dotnet-api
  template:
    metadata:
      labels:
        app: MyTrade-dotnet-api
    spec:
      containers:
      - name: MyTrade-dotnet-api
        image: acrfordeployment.azurecr.io/MyTrade-dotnet-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__SqlDb
          value: "Server=<Azure-SQL-Server-Connection>;Database=<Database-Name>;User Id=<User>;Password=<Password>"
        - name: ConnectionStrings__Redis
          value: "<Azure-Redis-Connection>"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
